-- 코드를 입력하세요
SELECT ICECREAM_INFO.FLAVOR FROM FIRST_HALF
JOIN ICECREAM_INFO ON FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
WHERE TOTAL_ORDER > 3000 and INGREDIENT_TYPE = 'fruit_based'
ORDER BY TOTAL_ORDER DESC
;
